### ISSUE TITLE
Error when deploying on Vercel

### ISSUE THREAD

**Issue by sabzo** [9d8dev/next-wp#13]
Hi -- I like the demo you created. I setup wordpress API and set permalink to postname. When I load my custom wordpress install on Vercel I get this error:

```
at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
    at successSteps (node:internal/deps/undici/undici:5454:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:5463:7)
    at async I (/vercel/path0/.next/server/chunks/806.js:1:7660)
    at async c (/vercel/path0/.next/server/app/posts/authors/page.js:1:3024) {
  digest: '325174538'
}
Error occurred prerendering page "/posts/authors". Read more: https://nextjs.org/docs/messages/prerender-error
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
    at successSteps (node:internal/deps/undici/undici:5454:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:5463:7)
    at async I (/vercel/path0/.next/server/chunks/806.js:1:7660)
    at async c (/vercel/path0/.next/server/app/posts/authors/page.js:1:3024)
   Generating static pages (9/12) 
 ✓ Generating static pages (12/12)
> Export encountered errors on following paths:
	/posts/authors/page: /posts/authors
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

[Runtime Logs](https://vercel.com/sabzos-projects/next-wp-jave/logs)
```

**Comment by youngbloodcyb** [comment]
Thanks for checking it out! 

I can dive into this. 

Just at first glance my guess is there is an error when fetching from the `authors` in WP and it's returning an HTML error page from WP. 

The structure of the authors could be different than what this repo is expecting and could be returning an HTML asset as an error response. If you try to hit the WP endpoint with Postman or another HTTP client does it give any more info? 

Does everything work in development and do you have a public WP URL I can use for debugging?

**Comment by sabzo** [comment]
@youngbloodcyb no prob! Yes everything works in development on the wordpress side, not when mixing with nextjs. Here's the URL I'm currently examining https://juniper.villagespring.com. Thnx!

**Comment by Shaxadhere** [comment]
Hi @sabzo 

I ran into the similar problem while deploying it on vercel and solved it using following steps.

- login to your **Wordpress admin**
- go to **settings** -> **Permalinks**
- set **permalink structure** to **Day and name**

**Comment by sabzo** [comment]
@Shaxadhere @youngbloodcyb I ran the install locally and debugged -- turns out there was a server issue where the authors route was returning a 403

![image](https://github.com/user-attachments/assets/47e64674-0588-457c-bd50-7715561134f3)

```

Error 403 - Forbidden access.
Sorry, you do not have permission to access this resource on the server due to a security restriction.

If you are the site owner, please check your site management tools to verify your WAF settings or contact us if the problem persists.
```

closing issue as this is due to server setup!

thnx
