### ISSUE TITLE
URL CORRECT BUT RETURNING NOT VALID JSON

### ISSUE THREAD

**Issue by esilverman682** [9d8dev/next-wp#31]
I added the .env details for the Url and \graphql as well however i get errors on the build and retrieval of postsm pages, authors and categories.  
✓ Compiled /posts in 165ms
 ⨯ SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at async getAllPosts (lib/wordpress.ts:35:24)
    at async Page (app/posts/page.tsx:34:16)
  33 |   const url = getUrl("/wp-json/wp/v2/posts", { author: filterParams?.author, tags: filterParams?.tag, categories: filterParams?.category });
  34 |   const response = await fetch(url);
> 35 |   const posts: Post[] = await response.json();
     |                        ^
  36 |   return posts;
  37 | }
  38 | {
  digest: '3000570245'
}

**Comment by brijr** [comment]
This usually occurs when the RestAPI is not enabled on your WP. Can you try this and see if it works? 

🔗 https://www.perplexity.ai/search/how-to-enable-the-wordpress-re-olXm9RZlQtymdv12amrW0A 

Check and see if plugins are disabling the API

**Comment by youngbloodcyb** [comment]
This project doesn't support graphql, just the Wordpress rest api
